### ISSUE TITLE
Is this an bug? can't pass information between different functions in class Protocol(ProtocolBase)

### ISSUE THREAD

**Issue by muyufan** [ashdnazg/pyreshark#15]
In doc "Writing Dissectors"  https://github.com/ashdnazg/pyreshark/wiki/Writing-Dissectors
said:
"You can pass information between different functions by storing it in the Protocol object (accessible through self), just make sure you reset your value when dissecting a new packet, as the same Protocol object is used for dissecting all packets."

But this only works when pass information between function like this: def function(self, packet):
Can't access self.infomation between function whitout paramater like : def function(self):

class Protocol(ProtocolBase):
    def __init__(self):        
        self._name = "x Protocol"
        self._filter_name = "x"
        self._short_name = "x"
        self._register_under = {"tcp.port": 8000}
        self._items = []
        self.set_items()

    def set_items(self):
        self._items.extend(self.message_header())
        self._items.extend(self.message_body())

    def message_header(self):
        return [
            FieldItem("identifier", FT_STRING, "identifier", length=4),
            PyFunctionItem(self.dissect_type, {
                "key_message_type": FieldItem("message_type", FT_UINT16, "message_type", strings=MESSAGE_TYPE, display=BASE_HEX)
            }),            
            FieldItem("length", FT_UINT16, "length")         
        ]

    def dissect_type(self, packet):
        packet.read_item("key_message_type")
        (self._message_type,) = struct.unpack("<h", packet.buffer[6:8])

    def message_body(self):
       logger.info("I can't see infomatio:" + self._message_type)
        return [
            PyFunctionItem(self.dissect_body, {
            FieldItem("checksum", FT_UINT16, "checksum"),
            })
        ]  

    def dissect_body(self, packet):
        logger.info("I can see infomatio:" + self._message_type)

**Comment by ashdnazg** [comment]
The message_body function is called by the __init__ function, in Wireshark's startup when it registers all protocols.

The dissect_type function is called for every dissected packet, obviously after message_body was called.
Unfortunately information can't go back in time...
