### ISSUE TITLE
make fails for pyreshark

### ISSUE THREAD

**Issue by praveenHp** [ashdnazg/pyreshark#16]
Hi,

I followed all steps provided in https://code.google.com/p/pyreshark/wiki/BuildingPyreshark  . But when I tried to build it calling the make of "wireshark", I'm getting the following error.

   Making all in pyreshark
    make[3]: Entering directory `/home/paavu/wireshark/plugins/pyreshark'
    CC       plugin.lo
   CC       pyreshark.lo
   CC       python_loader.lo
   CCLD     pyreshark.la
    /usr/bin/python generate_ws_consts.py python/cal/ws_consts.py
    cp templates/ws_types.py.1_99 python/cal/ws_types.py
    cp: cannot stat ‘templates/ws_types.py.1_99’: No such file or directory
    make[3]: *** [ws_types] Error 1
    make[3]: Leaving directory `/home/paavu/wireshark/plugins/pyreshark'
    make[2]: *** [all-recursive] Error 1
    make[2]: Leaving directory `/home/paavu/wireshark/plugins'
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory `/home/paavu/wireshark'
    make: *** [all] Error 2

In templates directory, I don't find ws_types.py.1_99. Is this file created dynamically? Or can we rename one of the files under templates directory?

System details:
Ubuntu 14.04
Pyreshark version - 0.1.4 (as per Changelog file)
wireshark version "v1.99.6rc0-48-g8204578"

**Comment by ashdnazg** [comment]
Hey,
You're not on one of Wireshark's release branches (1.12 or 1.10) but on a development branch (1.99) which isn't supported.

**Comment by praveenHp** [comment]
Thanks. Would be of great help if you add this information in the documentation.

**Comment by ashdnazg** [comment]
Good idea, thanks!
