### ISSUE TITLE
 IOError while running wireshark from build directory for pyreshark

### ISSUE THREAD

**Issue by praveenHp** [ashdnazg/pyreshark#17]
Hi, 

Firstly, apologies for asking trivial questions! 

I'm trying to build wireshark after building from pyreshark. When I run the command `WIRESHARK_RUN_FROM_BUILD_DIRECTORY=1 ./wireshark`

I get the following error.

 `Can't open Pyreshark init file: /home/paavu/wireshark-1.12.4/python/pyreshark.py
    IOError: [Errno 2] No such file or directory: '/home/paavu/wireshark-1.12.4/python/pyreshark.py'`

The actual path of pyreshark.py is `wireshark-1.12.4/plugins/pyreshark/python/pyreshark.py`

Any help is appreciated.

Regards,
Praveen

**Comment by ashdnazg** [comment]
Oh, I never even knew WIRESHARK_RUN_FROM_BUILD_DIRECTORY exists, so I never tried to support it.

Copying the python folder manually into wireshark-1.12.4/python (so it's wireshark-1.12.4/python/cal) may work.

**Comment by praveenHp** [comment]
I'll try the hack but what is the other way? `make install`??

**Comment by ashdnazg** [comment]
yup

**Comment by praveenHp** [comment]
Thanks. I used `make install` and it worked

**Comment by ashdnazg** [comment]
Great :)
