### ISSUE TITLE
Weird set_next_dissector behavior?

### ISSUE THREAD

**Issue by ijs6** [ashdnazg/pyreshark#24]
I might be overlooking something _extremely_ simple... but I'm having some trouble setting the next dissector when passing a variable representing a string to the set_next_dissector() function, rather than a string itself. For instance:

self.set_next_dissector('protocol') works, while

self.set_next_dissector(protocol_name) does not, even if protocol_name == 'protocol' .

**Comment by ijs6** [comment]
Other than this I have had _zero_ problems getting dissectors to work properly.

**Comment by ijs6** [comment]
Fixed. There was an error in a a dissector being called later in the chain which I believe was preventing proper function

**Comment by ashdnazg** [comment]
Good job :)
