### ISSUE TITLE
Update pyreshark to Wireshark 1.12

### ISSUE THREAD

**Issue by wddozier** [ashdnazg/pyreshark#8]
plugin.c:44:24: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘const’
 WS_DLL_PUBLIC_NOEXTERN const gchar version[] = VERSION;
                        ^
plugin.c:48:24: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 WS_DLL_PUBLIC_NOEXTERN void
                        ^
plugin.c:54:24: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 WS_DLL_PUBLIC_NOEXTERN void
                        ^
$ gcc -v
Using built-in specs.
COLLECT_GCC=/usr/local/bin/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-unknown-linux-gnu/4.8.2/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ./configure --disable-gnu-unique-object --disable-multilib --enable-version-specific-runtime-libs --enable-languages=c,c++ --prefix=/usr --program-suffix=48
Thread model: posix
gcc version 4.8.2 (GCC)

**Comment by okkervil** [comment]
I am now writing a dissector using pyreshark, is there doc or any other sample dissector(such as tcp dissector)? Thank you!

**Comment by ashdnazg** [comment]
https://github.com/ashdnazg/pyreshark/wiki/Writing-Dissectors

**Comment by okkervil** [comment]
@ashdnazg Thanks a lot, but are there extra sample dissectors?

**Comment by ashdnazg** [comment]
I'm not familiar with any Open source ones except https://github.com/AdiKo/RPCSniffer/blob/master/pyreshark_rpc_dissector/rpc_protocol.py

**Comment by okkervil** [comment]
@ashdnazg Thanks again.

**Comment by ashdnazg** [comment]
Added in 0.1.4
